alias restart="clear && source ~/.bashrc"
alias py="python3.8"
alias oct="octave"
alias cg="cargo"
alias ps="powershell.exe"
alias cmd="cmd.exe"
alias wpy="powershell.exe -c python"
alias wjava="powershell.exe -c java"
alias wjavac="powershell.exe -c javac"
alias decache="sudo sh -c \"/bin/echo 3 > '/proc/sys/vm/drop_caches'\" && echo success"
alias swap_reset="sudo swapoff -a && sudo swapon -a && echo success"
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias krcp="powershell.exe -c 'cat C:\Users\ronak\Downloads\kr_settings.txt | clip'"
alias ngrok="~/ngrock/ngrok"
alias exp="explorer.exe"
alias raise-ulimit="su $(whoami) --shell /bin/bash"
alias catupload="/home/rbadhe/catuploader.bash"
alias snarf="/home/rbadhe/snarfer.bash"
alias zoom="/home/rbadhe/zoomselector.bash"
alias cim="sc-im"
alias post="curl --request POST --header \"Content-Type: application/json\""
alias sp="python3.8 ~/Workspace/spanishdict/spanishdict"
alias license="/home/rbadhe/.get-license.bash"
alias ree="printf 'リーーーーーーー' | powershell.exe -c clip"
alias rick="DISPLAY= mpv --quiet -vo caca 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
alias zeros="powershell.exe -c python ~/Workspace/Schoology-grades/schoology/grades.py"
alias ssreset="echo 'taskkill /f /IM explorer.exe' | ps -c clip"
alias soattend="/home/rbadhe/sciolyattendance.bash"
function cs() { curl -m 7 "https://cheat.sh/$1"; }
alias opinion="printf 'https://www.youtube.com/watch?v=CXArovLJ60A' | powershell.exe -c clip"
